'use strict';

/**
 * The booking lifecycle.
 *
 * ┌──────────┐  hold   ┌──────┐  create  ┌─────────────────┐  pay   ┌───────────┐
 * │ AVAILABLE│────────▶│ HELD │─────────▶│ PENDING_PAYMENT │───────▶│ CONFIRMED │
 * └──────────┘         └──────┘          └─────────────────┘        └───────────┘
 *       ▲                  │                      │                       │
 *       │  expire/release  │        expire/fail   │             check-in  │
 *       └──────────────────┴──────────────────────┘                       ▼
 *                                                                  ┌────────────┐
 *                                    cancel ◀────────────────────  │ CHECKED_IN │
 *                                                                  └────────────┘
 *                                                                         │
 *                                                             check-out   ▼
 *                                                                  ┌───────────┐
 *                                                                  │ COMPLETED │
 *                                                                  └───────────┘
 *
 * Four invariants, each of which the previous implementation broke:
 *
 *   1. THE SERVER DECIDES THE AMOUNT. A request never carries a price. The quote
 *      is recomputed here and stored on the booking; the payment order is created
 *      from that stored number.
 *
 *   2. THE SERVER DECIDES WHOSE BOOKING IT IS. Every read and every transition is
 *      predicated on `user_id`. The old API identified a customer by a phone number
 *      in the URL, so anyone could cancel anyone's booking.
 *
 *   3. NO STATE IS REACHED BY DELETION. Cancelling, expiring and completing are all
 *      `transition()` plus a `booking_events` row.
 *
 *   4. TRANSITIONS ARE CONDITIONAL AND THEREFORE IDEMPOTENT. `transition()` matches
 *      on the expected current status; a second concurrent attempt matches nothing
 *      and is reported as "already done", not as a failure.
 */

const { config } = require('../config');
const photos = require('../utils/publicUrl');
const db = require('../db');
const bookingRepository = require('../repositories/bookingRepository');
const paymentRepository = require('../repositories/paymentRepository');
const parkingRepository = require('../repositories/parkingRepository');
const slotRepository = require('../repositories/slotRepository');
const userRepository = require('../repositories/userRepository');
const pricingService = require('./pricingService');
const gateway = require('../sockets/gateway');
const time = require('../utils/time');
const money = require('../utils/money');
const { logger } = require('../utils/logger');
const {
  badRequest,
  notFound,
  forbidden,
  conflict,
  DomainErrors,
} = require('../utils/errors');

/* ── serialisation ─────────────────────────────────────────────────────────── */

/**
 * The booking as both apps consume it.
 *
 * Composite fields (`is_cancellable`, `can_check_in`) are computed here rather than
 * in each client, because the operator app and the customer app must agree about
 * them and a rule duplicated in two Dart codebases is a rule that will diverge.
 */
function serializeBooking(row, { now = time.nowUtc() } = {}) {
  if (!row) return null;

  const status = row.status;
  const entry = time.parseInstant(row.entry_time);
  const exit = time.parseInstant(row.expected_exit_time);

  const minutesToEntry = entry ? time.diffMinutes(entry, now) : null;
  const paid = row.payment_status === 'PAID';

  return {
    id: row.id,
    // The access credential. This is what the driver shows and the operator types
    // in — generated by the database, stable for the life of the booking.
    code: row.booking_code,
    status,
    status_label: statusLabel(status),

    parking: {
      id: row.parking_id,
      name: row.parking_name,
      address_line: row.parking_address_line ?? null,
      locality: row.parking_locality ?? null,
      city: row.parking_city ?? null,
      landmark: row.parking_landmark ?? null,
      contact_phone: row.parking_contact_phone ?? null,
      // Absolutised for the same reason as the discovery list: stored
      // root-relative so the row survives a host change, but a client's image
      // loader has no base to resolve against.
      cover_photo_url: photos.absolute(row.parking_cover_photo_url) ?? null,
      instructions: row.parking_instructions ?? null,
      location:
        row.parking_lat === null || row.parking_lat === undefined
          ? null
          : { lat: Number(row.parking_lat), lng: Number(row.parking_lng) },
    },

    slot: row.parking_slot_id
      ? {
          id: row.parking_slot_id,
          code: row.slot_code,
          row_label: row.slot_row ?? null,
          position: row.slot_position ?? null,
          slot_number: row.slot_number ?? null,
          slot_class: row.slot_class ?? 'standard',
        }
      : null,

    vehicle: {
      type: row.vehicle_type,
      // The plate saved on the booking; falls back to the saved-vehicle record.
      number_plate: row.number_plate || row.vehicle_plate || null,
      label: row.vehicle_label ?? null,
    },

    window: {
      entry_time: time.toIso(entry),
      expected_exit_time: time.toIso(exit),
      duration_minutes: row.duration_minutes,
      minutes_until_entry: minutesToEntry,
    },

    // Every amount the client shows comes from here. Nothing is computed app-side.
    amount: {
      reserved_paise: row.amount_paise ?? 0,
      reserved_display: money.formatPaise(row.amount_paise ?? 0),

      // The rate this booking was priced at, lifted from the snapshot taken
      // when it was created — NOT recomputed, and deliberately not left for the
      // client to derive by dividing the total by the hours. That division is
      // wrong the moment a booking has a platform fee, a surge multiplier or a
      // part-hour, and it would quietly disagree with the receipt.
      hourly_paise: row.pricing_snapshot?.hourly_price_paise ?? null,
      hourly_display:
        row.pricing_snapshot?.hourly_price_paise === undefined ||
        row.pricing_snapshot?.hourly_price_paise === null
          ? null
          : money.formatPaise(row.pricing_snapshot.hourly_price_paise),
      // Null until check-out; the client shows "Final amount" only once it exists.
      final_paise: row.final_amount_paise ?? null,
      final_display:
        row.final_amount_paise === null || row.final_amount_paise === undefined
          ? null
          : money.formatPaise(row.final_amount_paise),
      refunded_paise: row.payment_refunded_paise ?? 0,
      currency: row.currency || config.payments.currency,
    },

    payment: {
      status: row.payment_status ?? null,
      is_paid: paid,
      // The provider's own reference, for the customer's records and for support.
      reference: row.payment_reference ?? null,
      verified_at: row.payment_verified_at ? time.toIso(row.payment_verified_at) : null,
    },

    // Server-decided capabilities. The client enables a button when the server
    // says so; it never derives the rule itself.
    actions: {
      is_cancellable: isCancellable(status),
      can_check_in: canCheckIn({ status, entry, now }),
      can_check_out: status === 'CHECKED_IN',
      can_pay: status === 'PENDING_PAYMENT',
      can_review: status === 'COMPLETED',
    },

    checked_in_at: row.checked_in_at ? time.toIso(row.checked_in_at) : null,
    checked_out_at: row.checked_out_at ? time.toIso(row.checked_out_at) : null,
    completed_at: row.completed_at ? time.toIso(row.completed_at) : null,
    cancelled_at: row.cancelled_at ? time.toIso(row.cancelled_at) : null,
    cancelled_by: row.cancelled_by ?? null,
    cancellation_reason: row.cancellation_reason ?? null,

    pricing_snapshot: row.pricing_snapshot || {},
    checkout_snapshot: row.checkout_snapshot || {},

    source: row.source,
    created_at: time.toIso(row.created_at),
  };
}

function statusLabel(status) {
  switch (status) {
    case 'PENDING_PAYMENT':
      return 'Awaiting payment';
    case 'CONFIRMED':
      return 'Confirmed';
    case 'CHECKED_IN':
      return 'Parked';
    case 'COMPLETED':
      return 'Completed';
    case 'CANCELLED':
      return 'Cancelled';
    case 'EXPIRED':
      return 'Expired';
    case 'NO_SHOW':
      return 'Missed';
    default:
      return status || 'Unknown';
  }
}

function isCancellable(status) {
  return status === 'CONFIRMED' || status === 'PENDING_PAYMENT';
}

/**
 * Check-in is allowed from `checkInEarlyMinutes` before the entry time until
 * `checkInLateMinutes` after it. Outside that window the operator uses the
 * override path, which is audited separately.
 */
function canCheckIn({ status, entry, now = time.nowUtc() }) {
  if (status !== 'CONFIRMED' || !entry) return false;
  const minutes = time.diffMinutes(entry, now);
  if (minutes === null) return false;
  return minutes <= config.booking.checkInEarlyMinutes && minutes >= -config.booking.checkInLateMinutes;
}

/* ── holds ─────────────────────────────────────────────────────────────────── */

/**
 * Places a hold on a slot.
 *
 * This is the step the old system had no real equivalent of: it wrote a
 * `slot_holds` row with a phone string and no ownership, checked for conflicts
 * *before* `BEGIN`, and relied on `SELECT ... FOR UPDATE` — which locks nothing when
 * a slot has no rows yet, so two people picking the same free slot both succeeded.
 *
 * Here: advisory lock on the slot identity, re-check inside the lock, then insert.
 * The unique index `uq_slot_holds_one_active` is the backstop.
 *
 * The returned `expires_at` is a server timestamp. The countdown the customer sees
 * is driven from it, so a device with a wrong clock cannot believe it has longer.
 */
async function createHold({ userId, parkingAreaId, slotId, startAt, durationMinutes }) {
  const user = await userRepository.findById(userId);
  if (!user) throw notFound('Your account could not be found', 'USER_NOT_FOUND');

  const area = await parkingRepository.findRawById(parkingAreaId);
  if (!area || area.is_active === false) {
    throw notFound('That parking area is not available', 'PARKING_NOT_FOUND');
  }

  const slot = await slotRepository.findById(slotId);
  if (!slot) throw notFound('That slot does not exist', 'SLOT_NOT_FOUND');
  if (Number(slot.parking_area_id) !== Number(parkingAreaId)) {
    throw badRequest('That slot belongs to a different parking area', undefined, 'SLOT_AREA_MISMATCH');
  }
  if (!slot.is_active) {
    throw conflict('That slot is out of service', 'SLOT_CLOSED');
  }

  const start = time.parseInstant(startAt) || time.nowUtc();
  const duration = Number(durationMinutes) || config.booking.defaultDurationMinutes;
  const end = time.expectedExit(start, duration);

  assertWindowIsBookable({ start, duration, area });
  await assertLotIsOpen({ area, start, end });

  return db.withTransaction(async (tx) => {
    // Serialise on the identity of the slot, not on rows that happen to exist.
    await db.advisoryXactLock(tx, 'slot', slotId);

    // A user holding a slot may re-hold the same one (they came back to the screen);
    // holding a second slot releases the first, so one person cannot pin a lot.
    const existing = await slotRepository.findActiveHoldForUser(userId, tx);
    if (existing && Number(existing.parking_slot_id) !== Number(slotId)) {
      await slotRepository.releaseHold(
        { holdId: existing.id, userId, reason: 'replaced_by_new_hold' },
        tx
      );
      emitSlotAvailable(existing);
    }

    const freedom = await slotRepository.isFreeForWindow({
      slotId,
      startAt: start,
      endAt: end,
      ignoreHoldId: existing && Number(existing.parking_slot_id) === Number(slotId)
        ? existing.id
        : null,
      client: tx,
    });

    if (!freedom.free) {
      throw freedomToError(freedom.reason);
    }

    // Reuse rather than stack: returning to the screen should not create a second
    // hold row for the same slot.
    if (existing && Number(existing.parking_slot_id) === Number(slotId)) {
      await slotRepository.releaseHold(
        { holdId: existing.id, userId, reason: 'reissued' },
        tx
      );
    }

    const quote = await pricingService.quote({
      parkingArea: area,
      vehicleType: slot.vehicle_type,
      startAt: start,
      durationMinutes: duration,
      client: tx,
    });

    const hold = await slotRepository.createHold(
      {
        parkingAreaId,
        slotId,
        slotNumber: slot.slot_number,
        vehicleType: slot.vehicle_type,
        userId,
        phone: user.phone,
        entryTime: start,
        durationMinutes: duration,
        holdSeconds: config.booking.holdSeconds,
      },
      tx
    );

    // The quote shown next to the countdown is stored, so the Review screen and the
    // payment order cannot disagree — even if the user backgrounds the app and the
    // demand multiplier moves while they are away.
    await db.query(
      `UPDATE slot_holds SET quote_snapshot = $2 WHERE id = $1`,
      [hold.id, JSON.stringify(quote)],
      tx
    );

    gateway.emitSlotUpdate({
      parkingAreaId,
      vehicleType: slot.vehicle_type,
      slotId,
      slotNumber: slot.slot_number,
      slotCode: slot.code,
      status: 'held',
      heldByUserId: userId,
      expiresAt: time.toIso(hold.hold_expires_at),
    });

    return serializeHold({ hold, slot, area, quote });
  });
}

/** Serialises a hold with everything the countdown screen needs. */
function serializeHold({ hold, slot, area, quote }) {
  const expiresAt = time.parseInstant(hold.hold_expires_at);
  const now = time.nowUtc();

  return {
    id: hold.id,
    parking_area_id: hold.parking_id,
    parking_name: area?.name ?? null,
    slot: {
      id: slot.id,
      code: slot.code,
      row_label: slot.row_label,
      position: slot.position,
      slot_number: slot.slot_number,
      slot_class: slot.slot_class,
      vehicle_type: slot.vehicle_type,
    },
    window: {
      entry_time: time.toIso(hold.entry_time),
      duration_minutes: hold.duration_minutes,
      expected_exit_time: time.toIso(
        time.expectedExit(time.parseInstant(hold.entry_time), hold.duration_minutes)
      ),
    },
    // Absolute server instant plus the remaining seconds at the moment of the
    // response. The client ticks down from `expires_at`, not from `seconds_remaining`,
    // so a slow network does not silently extend the hold on screen.
    expires_at: time.toIso(expiresAt),
    seconds_remaining: Math.max(0, time.diffSeconds(expiresAt, now) ?? 0),
    server_time: time.toIso(now),
    extension_count: hold.extension_count ?? 0,
    max_extensions: config.booking.maxHoldExtensions,
    quote: quote ?? null,
  };
}

/** The caller's live hold, if any. Restores the countdown after an app restart. */
async function getActiveHold(userId) {
  const hold = await slotRepository.findActiveHoldForUser(userId);
  if (!hold) return null;

  const slot = await slotRepository.findById(hold.parking_slot_id);
  const area = await parkingRepository.findRawById(hold.parking_id);
  const stored = await db.queryOne('SELECT quote_snapshot FROM slot_holds WHERE id = $1', [hold.id]);

  return serializeHold({
    hold,
    slot,
    area,
    quote: stored?.quote_snapshot && Object.keys(stored.quote_snapshot).length
      ? stored.quote_snapshot
      : null,
  });
}

/**
 * Extends a hold once, while the customer is still choosing.
 *
 * Bounded by `maxHoldExtensions` so this cannot become an indefinite reservation
 * that nobody paid for.
 */
async function extendHold({ userId, holdId }) {
  return db.withTransaction(async (tx) => {
    const hold = await slotRepository.findHoldById(holdId, tx);
    if (!hold) throw notFound('That hold no longer exists', 'HOLD_NOT_FOUND');
    if (Number(hold.user_id) !== Number(userId)) throw forbidden('That hold is not yours', 'NOT_YOUR_HOLD');
    if (hold.consumed_at || hold.released_at) throw DomainErrors.holdExpired();
    if (time.isBefore(time.parseInstant(hold.hold_expires_at), time.nowUtc())) {
      throw DomainErrors.holdExpired();
    }

    const current = await db.queryOne(
      'SELECT extension_count FROM slot_holds WHERE id = $1 FOR UPDATE',
      [holdId],
      tx
    );

    if ((current?.extension_count ?? 0) >= config.booking.maxHoldExtensions) {
      throw conflict(
        'This slot cannot be held any longer. Please complete your booking.',
        'HOLD_EXTENSION_EXHAUSTED'
      );
    }

    const updated = await db.queryOne(
      `UPDATE slot_holds
          SET hold_expires_at = hold_expires_at + ($2 || ' seconds')::interval,
              extension_count = extension_count + 1
        WHERE id = $1 AND consumed_at IS NULL AND released_at IS NULL
        RETURNING id, parking_id, parking_slot_id, slot_number, vehicle_type, user_id,
                  entry_time, duration_minutes, hold_expires_at, extension_count`,
      [holdId, config.booking.holdExtensionSeconds],
      tx
    );

    if (!updated) throw DomainErrors.holdExpired();

    const slot = await slotRepository.findById(updated.parking_slot_id, tx);
    const area = await parkingRepository.findRawById(updated.parking_id, tx);

    gateway.emitSlotUpdate({
      parkingAreaId: updated.parking_id,
      vehicleType: updated.vehicle_type,
      slotId: updated.parking_slot_id,
      slotNumber: updated.slot_number,
      slotCode: slot?.code,
      status: 'held',
      heldByUserId: userId,
      expiresAt: time.toIso(updated.hold_expires_at),
    });

    return serializeHold({ hold: updated, slot, area, quote: null });
  });
}

/** Releases a hold the customer abandoned. Frees the slot immediately. */
async function releaseHold({ userId, holdId }) {
  const released = await slotRepository.releaseHold({ holdId, userId, reason: 'released_by_user' });
  if (!released) {
    // Already gone — expired, consumed, or never theirs. Releasing something that
    // is not held is not an error from the customer's point of view.
    return { released: false };
  }
  emitSlotAvailable(released);
  return { released: true };
}

function emitSlotAvailable(hold) {
  gateway.emitSlotUpdate({
    parkingAreaId: hold.parking_id,
    vehicleType: hold.vehicle_type,
    slotId: hold.parking_slot_id,
    slotNumber: hold.slot_number,
    status: 'available',
  });
}

/* ── booking creation ──────────────────────────────────────────────────────── */

/**
 * Converts a live hold into a PENDING_PAYMENT booking.
 *
 * The amount is recomputed here from the hold's stored quote — the request body
 * carries no price and there is no code path by which it could.
 *
 * Idempotent on `idempotencyKey`: a retry after a dropped response returns the
 * booking that was already created rather than making a second one.
 */
async function createFromHold({
  userId,
  holdId,
  vehicleId = null,
  numberPlate = null,
  notes = null,
  idempotencyKey = null,
}) {
  // Checked before the transaction so a retry is cheap and never touches the lock.
  if (idempotencyKey) {
    const existing = await bookingRepository.findByIdempotencyKey({ userId, key: idempotencyKey });
    if (existing) {
      logger.info({ bookingId: existing.id, userId }, 'Idempotent booking create — returning original');
      return { booking: serializeBooking(existing), created: false };
    }
  }

  const user = await userRepository.findById(userId);
  if (!user) throw notFound('Your account could not be found', 'USER_NOT_FOUND');

  const activeCount = await bookingRepository.countActiveForUser(userId);
  if (config.booking.maxActivePerUser > 0 && activeCount >= config.booking.maxActivePerUser) {
    throw conflict(
      `You already have ${activeCount} active bookings. Complete or cancel one to book again.`,
      'TOO_MANY_ACTIVE_BOOKINGS'
    );
  }

  const result = await db.withTransaction(async (tx) => {
    const hold = await slotRepository.findHoldById(holdId, tx);
    if (!hold) throw notFound('That hold no longer exists', 'HOLD_NOT_FOUND');
    if (Number(hold.user_id) !== Number(userId)) throw forbidden('That hold is not yours', 'NOT_YOUR_HOLD');
    if (hold.released_at) throw DomainErrors.holdExpired();
    if (hold.consumed_at) {
      // The hold already became a booking. Find it rather than failing: this is the
      // shape a duplicate submit takes when the client did not send a key.
      const already = await db.queryOne(
        `SELECT id FROM bookings WHERE slot_hold_id = $1 AND user_id = $2`,
        [holdId, userId],
        tx
      );
      if (already) return { bookingId: already.id, created: false };
      throw DomainErrors.holdExpired();
    }
    if (time.isBefore(time.parseInstant(hold.hold_expires_at), time.nowUtc())) {
      throw DomainErrors.holdExpired();
    }

    await db.advisoryXactLock(tx, 'slot', hold.parking_slot_id);

    const slot = await slotRepository.findById(hold.parking_slot_id, tx);
    const area = await parkingRepository.findRawById(hold.parking_id, tx);
    if (!slot || !area) throw notFound('That parking area is not available', 'PARKING_NOT_FOUND');

    const start = time.parseInstant(hold.entry_time);
    const duration = Number(hold.duration_minutes) || config.booking.defaultDurationMinutes;
    const end = time.expectedExit(start, duration);

    // The hold is ours, so it is excluded from the conflict check; anything else
    // overlapping means someone else's booking landed first.
    const freedom = await slotRepository.isFreeForWindow({
      slotId: hold.parking_slot_id,
      startAt: start,
      endAt: end,
      ignoreHoldId: hold.id,
      client: tx,
    });
    if (!freedom.free) throw freedomToError(freedom.reason);

    // Recomputed under the lock. The stored snapshot is what the customer was
    // shown; if the live price has moved against them we honour the snapshot,
    // because they agreed to that number. If it has moved in their favour they get
    // the lower one. Never the other way round.
    const stored = await db.queryOne('SELECT quote_snapshot FROM slot_holds WHERE id = $1', [hold.id], tx);
    const live = await pricingService.quote({
      parkingArea: area,
      vehicleType: slot.vehicle_type,
      startAt: start,
      durationMinutes: duration,
      client: tx,
    });

    const snapshotTotal = Number(stored?.quote_snapshot?.total_paise);
    const quote =
      Number.isFinite(snapshotTotal) && snapshotTotal > 0 && snapshotTotal < live.total_paise
        ? { ...stored.quote_snapshot, honoured_from_hold: true }
        : live;

    const vehicle = await resolveVehicle({ userId, vehicleId, numberPlate, vehicleType: slot.vehicle_type, client: tx });

    const created = await bookingRepository.create(
      {
        userId,
        parkingAreaId: hold.parking_id,
        slotId: hold.parking_slot_id,
        slotNumber: slot.slot_number,
        vehicleType: slot.vehicle_type,
        vehicleId: vehicle.id,
        numberPlate: vehicle.number_plate,
        phone: user.phone,
        entryTime: start,
        expectedExitTime: end,
        durationMinutes: duration,
        amountPaise: quote.total_paise,
        pricingSnapshot: quote,
        holdId: hold.id,
        idempotencyKey,
        source: 'customer_app',
      },
      tx
    );

    await slotRepository.consumeHold(hold.id, tx);

    await bookingRepository.recordEvent(
      {
        bookingId: created.id,
        eventType: 'created',
        toStatus: 'PENDING_PAYMENT',
        actorType: 'customer',
        actorId: userId,
        metadata: {
          hold_id: hold.id,
          amount_paise: quote.total_paise,
          multiplier: quote.multiplier,
          honoured_from_hold: quote.honoured_from_hold === true,
        },
      },
      tx
    );

    if (notes) {
      await db.query('UPDATE bookings SET notes = $2 WHERE id = $1', [created.id, String(notes).slice(0, 500)], tx);
    }

    return { bookingId: created.id, created: true, slot, area };
  });

  const row = await bookingRepository.findByIdForUser({ bookingId: result.bookingId, userId });

  if (result.created && result.slot) {
    gateway.emitSlotUpdate({
      parkingAreaId: row.parking_id,
      vehicleType: row.vehicle_type,
      slotId: row.parking_slot_id,
      slotNumber: row.slot_number,
      slotCode: result.slot.code,
      status: 'booked',
    });
  }

  return { booking: serializeBooking(row), created: result.created };
}

/**
 * Resolves which vehicle a booking is for.
 *
 * A saved vehicle is preferred; a typed plate is accepted and saved for next time,
 * because retyping a registration on every booking was one of the old flow's most
 * tedious steps.
 */
async function resolveVehicle({ userId, vehicleId, numberPlate, vehicleType, client }) {
  if (vehicleId) {
    const owned = await db.queryOne(
      'SELECT id, number_plate, vehicle_type FROM vehicles WHERE id = $1 AND user_id = $2',
      [vehicleId, userId],
      client
    );
    if (!owned) throw notFound('That vehicle is not on your account', 'VEHICLE_NOT_FOUND');
    if (owned.vehicle_type !== vehicleType) {
      throw badRequest(
        `That slot is for a ${vehicleType}. Pick a ${vehicleType} from your vehicles.`,
        undefined,
        'VEHICLE_TYPE_MISMATCH'
      );
    }
    return owned;
  }

  const plate = String(numberPlate || '').toUpperCase().replace(/\s+/g, '');
  if (!plate) {
    throw badRequest('Choose a vehicle or enter its number', undefined, 'VEHICLE_REQUIRED');
  }

  // Upsert on the same key the unique index uses, so booking twice with the same
  // plate does not create two vehicle records.
  const saved = await db.queryOne(
    `INSERT INTO vehicles (user_id, vehicle_type, number_plate, is_default)
     VALUES ($1, $2, $3, NOT EXISTS (
       SELECT 1 FROM vehicles WHERE user_id = $1 AND vehicle_type = $2 AND is_default
     ))
     ON CONFLICT (user_id, upper(replace(number_plate, ' ', '')))
     DO UPDATE SET updated_at = NOW()
     RETURNING id, number_plate, vehicle_type`,
    [userId, vehicleType, plate],
    client
  );

  return saved;
}

/* ── lifecycle transitions ─────────────────────────────────────────────────── */

/**
 * Moves a paid booking to CONFIRMED.
 *
 * Called only by paymentService, after a signature has actually been verified —
 * there is no route that reaches this with a client-supplied "payment succeeded".
 */
async function confirmPaid({ bookingId, paymentId, actorType = 'system', client = null }) {
  const run = async (tx) => {
    const moved = await bookingRepository.transition({
      bookingId,
      from: ['PENDING_PAYMENT'],
      to: 'CONFIRMED',
      client: tx,
    });

    if (!moved) {
      // Already confirmed by the other settlement path, or no longer pending.
      const current = await bookingRepository.findByIdUnscoped(bookingId, tx);
      return { booking: current, changed: false };
    }

    await bookingRepository.recordEvent(
      {
        bookingId,
        eventType: 'payment_confirmed',
        fromStatus: 'PENDING_PAYMENT',
        toStatus: 'CONFIRMED',
        actorType,
        metadata: { payment_id: paymentId },
      },
      tx
    );

    const current = await bookingRepository.findByIdUnscoped(bookingId, tx);
    return { booking: current, changed: true };
  };

  const result = client ? await run(client) : await db.withTransaction(run);

  if (result.changed && result.booking) {
    gateway.emitBookingUpdate(result.booking.user_id, serializeBooking(result.booking));
    gateway.emitOwnerBookingUpdate(result.booking.parking_owner_id, {
      type: 'booking_confirmed',
      booking: serializeBooking(result.booking),
    });
  }

  return result;
}

/**
 * Cancels a booking.
 *
 * Records the refund obligation whether or not the gateway call is enabled, and
 * frees the slot. The old implementation deleted the row, archived nothing on some
 * paths, and never told the customer what they would get back.
 */
async function cancel({ userId, bookingId, reason = null, actorType = 'customer', actorId = null }) {
  const result = await db.withTransaction(async (tx) => {
    const row = await bookingRepository.findByIdForUser({ bookingId, userId, client: tx });
    if (!row) throw notFound('That booking could not be found', 'BOOKING_NOT_FOUND');
    if (!isCancellable(row.status)) throw DomainErrors.bookingNotCancellable(row.status);

    const refund = pricingService.refundQuote({
      amountPaise: row.amount_paise ?? 0,
      entryAt: row.entry_time,
    });

    const moved = await bookingRepository.transition({
      bookingId,
      from: ['CONFIRMED', 'PENDING_PAYMENT'],
      to: 'CANCELLED',
      patch: {
        cancelled_at: new Date(),
        cancelled_by: actorType,
        cancellation_reason: reason ? String(reason).slice(0, 300) : null,
      },
      client: tx,
    });

    if (!moved) {
      // Someone else cancelled it in the meantime. Report the current state rather
      // than an error the customer cannot act on.
      const current = await bookingRepository.findByIdForUser({ bookingId, userId, client: tx });
      return { row: current, refund: null, changed: false };
    }

    // Money owed is recorded even when refunds are not being dispatched yet, so the
    // obligation lives in the database rather than in someone's memory.
    let refundRecord = null;
    if (row.payment_status === 'PAID' && refund.refund_paise > 0) {
      const payment = await paymentRepository.findPaidForBooking(bookingId, tx);
      if (payment) {
        refundRecord = await paymentRepository.createRefund(
          {
            paymentId: payment.id,
            bookingId,
            amountPaise: refund.refund_paise,
            reason: reason || 'customer_cancelled',
            status: config.features.refundsEnabled ? 'PENDING' : 'PENDING',
          },
          tx
        );
      }
    }

    // An unpaid booking's open order is closed so it cannot be paid after the fact.
    if (row.status === 'PENDING_PAYMENT') {
      await paymentRepository.abandonOpenOrders({ bookingId, reason: 'booking_cancelled' }, tx);
    }

    await bookingRepository.recordEvent(
      {
        bookingId,
        eventType: 'cancelled',
        fromStatus: row.status,
        toStatus: 'CANCELLED',
        actorType,
        actorId: actorId ?? userId,
        metadata: {
          reason,
          refund_percent: refund.refund_percent,
          refund_paise: refund.refund_paise,
          refund_id: refundRecord?.id ?? null,
        },
      },
      tx
    );

    const current = await bookingRepository.findByIdForUser({ bookingId, userId, client: tx });
    return { row: current, refund, changed: true };
  });

  if (result.changed && result.row) {
    gateway.emitSlotUpdate({
      parkingAreaId: result.row.parking_id,
      vehicleType: result.row.vehicle_type,
      slotId: result.row.parking_slot_id,
      slotNumber: result.row.slot_number,
      slotCode: result.row.slot_code,
      status: 'available',
    });
    gateway.emitBookingUpdate(userId, serializeBooking(result.row));
    gateway.emitOwnerBookingUpdate(result.row.parking_owner_id, {
      type: 'booking_cancelled',
      booking: serializeBooking(result.row),
    });
  }

  return {
    booking: serializeBooking(result.row),
    refund: result.refund,
    changed: result.changed,
  };
}

/**
 * Previews a cancellation without performing it.
 *
 * So the confirm dialog can state the actual refund rather than asking someone to
 * agree to an unknown outcome.
 */
async function cancellationPreview({ userId, bookingId }) {
  const row = await bookingRepository.findByIdForUser({ bookingId, userId });
  if (!row) throw notFound('That booking could not be found', 'BOOKING_NOT_FOUND');

  const refund = pricingService.refundQuote({
    amountPaise: row.amount_paise ?? 0,
    entryAt: row.entry_time,
  });

  return {
    is_cancellable: isCancellable(row.status),
    status: row.status,
    // Only meaningful when money actually changed hands.
    was_paid: row.payment_status === 'PAID',
    ...refund,
    refund_display: money.formatPaise(refund.refund_paise),
    retained_display: money.formatPaise(refund.retained_paise),
  };
}

/**
 * Check-in. Performed by the customer on arrival or by the operator at the barrier.
 *
 * `actorType` distinguishes the two in the audit trail, which matters in a dispute
 * about whether a car was ever actually there.
 */
async function checkIn({ bookingId, userId = null, ownerId = null, actorType = 'customer', force = false }) {
  const result = await db.withTransaction(async (tx) => {
    const row = userId
      ? await bookingRepository.findByIdForUser({ bookingId, userId, client: tx })
      : await bookingRepository.findByIdUnscoped(bookingId, tx);

    if (!row) throw notFound('That booking could not be found', 'BOOKING_NOT_FOUND');
    if (ownerId && Number(row.parking_owner_id) !== Number(ownerId)) {
      throw forbidden('That booking is not for your parking area', 'NOT_YOUR_PARKING_AREA');
    }
    if (row.status === 'CHECKED_IN') return { row, changed: false };
    if (row.status !== 'CONFIRMED') throw DomainErrors.invalidTransition(row.status, 'CHECKED_IN');

    const entry = time.parseInstant(row.entry_time);
    if (!force && !canCheckIn({ status: row.status, entry })) {
      const minutes = time.diffMinutes(entry, time.nowUtc());
      throw conflict(
        minutes > config.booking.checkInEarlyMinutes
          ? `Check-in opens ${config.booking.checkInEarlyMinutes} minutes before your entry time`
          : 'This booking is past its check-in window. Please speak to the operator.',
        'OUTSIDE_CHECK_IN_WINDOW',
        { minutes_until_entry: minutes }
      );
    }

    const moved = await bookingRepository.transition({
      bookingId,
      from: ['CONFIRMED'],
      to: 'CHECKED_IN',
      patch: {
        checked_in_at: new Date(),
        checked_in_by_owner_id: ownerId,
      },
      client: tx,
    });

    if (!moved) {
      const current = await bookingRepository.findByIdUnscoped(bookingId, tx);
      return { row: current, changed: false };
    }

    await bookingRepository.recordEvent(
      {
        bookingId,
        eventType: 'checked_in',
        fromStatus: 'CONFIRMED',
        toStatus: 'CHECKED_IN',
        actorType,
        actorId: ownerId ?? userId,
        metadata: { forced: force === true },
      },
      tx
    );

    const current = await bookingRepository.findByIdUnscoped(bookingId, tx);
    return { row: current, changed: true };
  });

  if (result.changed && result.row) {
    gateway.emitSlotUpdate({
      parkingAreaId: result.row.parking_id,
      vehicleType: result.row.vehicle_type,
      slotId: result.row.parking_slot_id,
      slotNumber: result.row.slot_number,
      slotCode: result.row.slot_code,
      status: 'booked',
    });
    gateway.emitBookingUpdate(result.row.user_id, serializeBooking(result.row));
    gateway.emitOwnerBookingUpdate(result.row.parking_owner_id, {
      type: 'checked_in',
      booking: serializeBooking(result.row),
    });
  }

  return { booking: serializeBooking(result.row), changed: result.changed };
}

/**
 * Check-out, and the final amount.
 *
 * The amount comes from `pricingService.finalAmount`, which the client cannot
 * influence. This replaces the operator app computing `amount = seconds parked` —
 * one rupee per second, so an hour billed as ₹3,600 — and the server then taking
 * `Math.max(server, client)`, which let that number win.
 */
async function checkOut({ bookingId, userId = null, ownerId = null, actorType = 'customer' }) {
  const result = await db.withTransaction(async (tx) => {
    const row = userId
      ? await bookingRepository.findByIdForUser({ bookingId, userId, client: tx })
      : await bookingRepository.findByIdUnscoped(bookingId, tx);

    if (!row) throw notFound('That booking could not be found', 'BOOKING_NOT_FOUND');
    if (ownerId && Number(row.parking_owner_id) !== Number(ownerId)) {
      throw forbidden('That booking is not for your parking area', 'NOT_YOUR_PARKING_AREA');
    }
    if (row.status === 'COMPLETED') return { row, changed: false };
    if (row.status !== 'CHECKED_IN') throw DomainErrors.invalidTransition(row.status, 'COMPLETED');

    const area = await parkingRepository.findRawById(row.parking_id, tx);
    const exitAt = time.nowUtc();

    const settlement = pricingService.finalAmount({
      booking: { ...row, entry_time: row.checked_in_at || row.entry_time },
      exitAt,
      parkingArea: area,
    });

    const moved = await bookingRepository.transition({
      bookingId,
      from: ['CHECKED_IN'],
      to: 'COMPLETED',
      patch: {
        completed_at: exitAt,
        checked_out_at: exitAt,
        exit_time: exitAt,
        checked_out_by_owner_id: ownerId,
        final_amount_paise: settlement.total_paise,
        checkout_snapshot: JSON.stringify(settlement),
      },
      client: tx,
    });

    if (!moved) {
      const current = await bookingRepository.findByIdUnscoped(bookingId, tx);
      return { row: current, changed: false, settlement: null };
    }

    await bookingRepository.recordEvent(
      {
        bookingId,
        eventType: 'checked_out',
        fromStatus: 'CHECKED_IN',
        toStatus: 'COMPLETED',
        actorType,
        actorId: ownerId ?? userId,
        metadata: settlement,
      },
      tx
    );

    // Popularity is a real count of completed stays, not the constant zero the old
    // API returned for a column that never existed.
    await db.query(
      'UPDATE parking_areas SET popularity_score = popularity_score + 1 WHERE id = $1',
      [row.parking_id],
      tx
    );

    const current = await bookingRepository.findByIdUnscoped(bookingId, tx);
    return { row: current, changed: true, settlement };
  });

  if (result.changed && result.row) {
    gateway.emitSlotUpdate({
      parkingAreaId: result.row.parking_id,
      vehicleType: result.row.vehicle_type,
      slotId: result.row.parking_slot_id,
      slotNumber: result.row.slot_number,
      slotCode: result.row.slot_code,
      status: 'available',
    });
    gateway.emitBookingUpdate(result.row.user_id, serializeBooking(result.row));
    gateway.emitOwnerBookingUpdate(result.row.parking_owner_id, {
      type: 'checked_out',
      booking: serializeBooking(result.row),
    });
  }

  return {
    booking: serializeBooking(result.row),
    settlement: result.settlement,
    changed: result.changed,
  };
}

/* ── reads ─────────────────────────────────────────────────────────────────── */

async function listForUser({ userId, bucket, limit = 20, offset = 0 }) {
  const rows = await bookingRepository.listForUser({ userId, bucket, limit, offset });
  const hasMore = rows.length > limit;
  const page = hasMore ? rows.slice(0, limit) : rows;

  return {
    items: page.map((r) => serializeBooking(r)),
    page: { limit, offset, has_more: hasMore },
  };
}

async function getForUser({ userId, bookingId }) {
  const row = await bookingRepository.findByIdForUser({ bookingId, userId });
  if (!row) throw notFound('That booking could not be found', 'BOOKING_NOT_FOUND');

  const [events, refunds] = await Promise.all([
    bookingRepository.listEvents(bookingId),
    paymentRepository.listRefundsForBooking(bookingId),
  ]);

  return {
    ...serializeBooking(row),
    // The timeline the customer sees on the booking detail screen. Only the events
    // that mean something to them; internal ones stay in the table.
    timeline: events
      .filter((e) => CUSTOMER_VISIBLE_EVENTS.has(e.event_type))
      .map((e) => ({
        type: e.event_type,
        label: eventLabel(e.event_type),
        at: time.toIso(e.created_at),
      })),
    refunds: refunds.map((r) => ({
      id: r.id,
      amount_paise: r.amount_paise,
      amount_display: money.formatPaise(r.amount_paise),
      status: r.status,
      processed_at: r.processed_at ? time.toIso(r.processed_at) : null,
    })),
  };
}

const CUSTOMER_VISIBLE_EVENTS = new Set([
  'created',
  'payment_confirmed',
  'checked_in',
  'checked_out',
  'cancelled',
  'expired',
  'no_show',
]);

function eventLabel(type) {
  switch (type) {
    case 'created':
      return 'Booking created';
    case 'payment_confirmed':
      return 'Payment confirmed';
    case 'checked_in':
      return 'Checked in';
    case 'checked_out':
      return 'Checked out';
    case 'cancelled':
      return 'Cancelled';
    case 'expired':
      return 'Expired — payment not completed';
    case 'no_show':
      return 'Marked as missed';
    default:
      return type;
  }
}

async function getCountsForUser(userId) {
  return bookingRepository.countsForUser(userId);
}

/** The active-parking card on Home. Returns null when there is nothing to show. */
async function getCurrentForUser(userId) {
  const row = await bookingRepository.findCurrentForUser({
    userId,
    earlyMinutes: config.booking.checkInEarlyMinutes,
  });
  if (!row) return null;

  const booking = serializeBooking(row);

  // Live elapsed/remaining, computed server-side so two devices agree.
  if (row.status === 'CHECKED_IN' && row.checked_in_at) {
    const now = time.nowUtc();
    const elapsed = time.diffMinutes(now, time.parseInstant(row.checked_in_at)) ?? 0;
    const reserved = Number(row.duration_minutes) || 0;

    // What they would owe if they left this minute — the same function check-out
    // itself uses, so the figure on the Home card is the figure they are charged.
    // The old operator app computed `amount = seconds parked`, billing an hour as
    // ₹3,600, and the server then took Math.max(server, client).
    const area = await parkingRepository.findRawById(row.parking_id);
    const projected = pricingService.finalAmount({
      booking: { ...row, entry_time: row.checked_in_at },
      exitAt: now,
      parkingArea: area,
    });

    booking.session = {
      elapsed_minutes: Math.max(0, elapsed),
      reserved_minutes: reserved,
      remaining_minutes: Math.max(0, reserved - elapsed),
      is_overstaying: elapsed > reserved,
      projected_total_paise: projected.total_paise,
      projected_total_display: money.formatPaise(projected.total_paise),
      // Non-zero only once they are past their booked window. The client shows the
      // line only when there is one.
      overstay_paise: projected.overstay_paise,
      overstay_display:
        projected.overstay_paise > 0 ? money.formatPaise(projected.overstay_paise) : null,
    };
  }

  return booking;
}

/* ── helpers ───────────────────────────────────────────────────────────────── */

/** Turns a repository freedom reason into the right domain error. */
function freedomToError(reason) {
  switch (reason) {
    case 'SLOT_NOT_FOUND':
      return notFound('That slot does not exist', 'SLOT_NOT_FOUND');
    case 'SLOT_CLOSED':
      return conflict('That slot is out of service', 'SLOT_CLOSED');
    case 'SLOT_HELD':
      return DomainErrors.slotHeldByAnother();
    case 'SLOT_BOOKED':
      return DomainErrors.timeOverlap();
    default:
      return DomainErrors.slotUnavailable();
  }
}

/**
 * Refuses a window the lot is closed for.
 *
 * Separate from `assertWindowIsBookable` because it needs a query, and async. This
 * is what stops an operator's opening hours being advisory: before it existed, a
 * lot could be marked closed on Sunday and still take Sunday bookings, because
 * hours were only consulted by the discovery filter — a customer who deep-linked
 * past discovery was never checked at all.
 */
async function assertLotIsOpen({ area, start, end }) {
  // eslint-disable-next-line global-require
  const configRepository = require('../repositories/configRepository');

  const result = await configRepository.isOpenForWindow({
    parkingAreaId: area.id,
    startAt: start,
    endAt: end,
  });

  if (result.open) return;

  // Say WHICH day, using the lot's own local day rather than the server's.
  const localStart = time.addMinutes(start, Number(area.timezone_offset_minutes) || 0);
  const dayOfWeek = localStart.getUTCDay();
  const hours = await configRepository.openingHoursFor({
    parkingAreaId: area.id,
    dayOfWeek,
  });

  const dayName = [
    'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
  ][dayOfWeek];

  throw conflict(
    hours
      ? `This parking area is open ${String(hours.opens_at).slice(0, 5)}–` +
          `${String(hours.closes_at).slice(0, 5)} on ${dayName}. Pick a time inside that.`
      : `This parking area is closed on ${dayName}.`,
    'PARKING_CLOSED',
    { day_of_week: dayOfWeek }
  );
}

/** Window rules, applied identically to holds and to bookings. */
function assertWindowIsBookable({ start, duration, area }) {
  const now = time.nowUtc();

  // A small negative tolerance: the user tapped "now" a few seconds ago and the
  // request took time to arrive. Anything further back is a real mistake.
  const minutesFromNow = time.diffMinutes(start, now) ?? 0;
  if (minutesFromNow < -5) {
    throw badRequest('That start time is in the past', undefined, 'START_TIME_IN_PAST');
  }

  const maxAdvance = config.booking.maxAdvanceDays * 24 * 60;
  if (minutesFromNow > maxAdvance) {
    throw badRequest(
      `Bookings can be made up to ${config.booking.maxAdvanceDays} days ahead`,
      undefined,
      'BOOKING_TOO_FAR_AHEAD'
    );
  }

  const areaMax = Number(area?.max_duration_minutes);
  const limit = Number.isFinite(areaMax) && areaMax > 0 ? areaMax : config.booking.maxDurationMinutes;
  if (duration > limit) {
    throw badRequest(
      `This parking area allows a maximum stay of ${Math.round(limit / 60)} hours`,
      undefined,
      'DURATION_EXCEEDS_LIMIT'
    );
  }
}

module.exports = {
  // holds
  createHold,
  getActiveHold,
  extendHold,
  releaseHold,
  // bookings
  createFromHold,
  confirmPaid,
  cancel,
  cancellationPreview,
  checkIn,
  checkOut,
  listForUser,
  getForUser,
  getCountsForUser,
  getCurrentForUser,
  // shared with the payment service and the operator routes
  serializeBooking,
  isCancellable,
  canCheckIn,
};
